"""
config.py -- Centralized configuration for the Agentic RAG system.

All tunable parameters live here. Override via environment variables
with the prefix RAG_ (e.g., RAG_CHUNK_SIZE=600).

Usage:
    from src.core.config import config
    print(config.top_k)  # reads from env or default
"""

import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Project root: config is at src/core/config.py → root is 3 levels up
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


def _detect_best_device() -> str:
    """Detect the best available torch device at runtime.

    Priority: CUDA GPU → MPS (Apple Silicon) → CPU.
    Uses print() in addition to logging so the message is visible even
    before logging.basicConfig() has been called.

    Returns:
        One of 'cuda', 'mps', or 'cpu'.
    """
    try:
        import torch

        if torch.cuda.is_available():
            device_name = torch.cuda.get_device_name(0) or "CUDA GPU"
            msg = f"[device] cuda ({device_name})"
            print(msg, flush=True)
            logger.info("Embedding device: cuda (%s)", device_name)
            return "cuda"

        if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
            msg = "[device] mps (Apple Metal)"
            print(msg, flush=True)
            logger.info("Embedding device: mps (Apple Metal)")
            return "mps"

        msg = (
            "[device] CPU — WARNING: No GPU detected. "
            "Embedding will be significantly slower. "
            "If you have an NVIDIA GPU, install PyTorch with CUDA: "
            "pip install torch --index-url https://download.pytorch.org/whl/cu121"
        )
        print(msg, flush=True)
        logger.warning(
            "No GPU detected (CUDA unavailable, MPS unavailable). "
            "Embedding will run on CPU — this will be significantly slower. "
            "If you have an NVIDIA GPU, install PyTorch with CUDA support: "
            "pip install torch --index-url https://download.pytorch.org/whl/cu121"
        )
        return "cpu"

    except ImportError:
        msg = "[device] CPU — PyTorch not installed"
        print(msg, flush=True)
        logger.warning(
            "PyTorch not installed. Embedding will fall back to CPU if "
            "sentence-transformers manages to load without it."
        )
        return "cpu"


@dataclass
class RAGConfig:
    """Central configuration for the Agentic RAG pipeline.

    Every field is overridable via a RAG_<UPPER_FIELD> environment variable.
    Paths resolve lazily via default_factory to be relative to this file's location.
    """

    # ------------------------------------------------------------------
    # Paths
    # ------------------------------------------------------------------
    base_dir: Path = field(default_factory=lambda: Path(
        os.environ.get("RAG_BASE_DIR", str(_PROJECT_ROOT))
    ))
    data_dir: Path = field(default_factory=lambda: Path(
        os.environ.get(
            "RAG_DATA_DIR",
            str(_PROJECT_ROOT / "veracier-industries" / "by_entity" / "by_entity"),
        )
    ))
    master_index_path: Path = field(default_factory=lambda: Path(
        os.environ.get(
            "RAG_MASTER_INDEX",
            str(_PROJECT_ROOT / "veracier-industries" / "MASTER_INDEX.csv"),
        )
    ))
    answer_key_path: Path = field(default_factory=lambda: Path(
        os.environ.get(
            "RAG_ANSWER_KEY",
            str(_PROJECT_ROOT / "veracier-industries" / "ANSWER_KEY.json"),
        )
    ))

    # Output file paths (generated by data_prepare.py)
    chunk_jsonl_path: Path = field(default_factory=lambda: Path(
        os.environ.get("RAG_CHUNK_JSONL", str(_PROJECT_ROOT / "chunks.jsonl"))
    ))
    faiss_index_path: Path = field(default_factory=lambda: Path(
        os.environ.get("RAG_FAISS_INDEX", str(_PROJECT_ROOT / "faiss.index"))
    ))
    bm25_index_path: Path = field(default_factory=lambda: Path(
        os.environ.get("RAG_BM25_INDEX", str(_PROJECT_ROOT / "bm25_index.pkl"))
    ))

    # ------------------------------------------------------------------
    # Chunking parameters
    # ------------------------------------------------------------------
    chunk_size: int = int(os.environ.get("RAG_CHUNK_SIZE", "512"))
    """Maximum chunk size in tokens (approximate, via tiktoken)."""

    chunk_overlap: int = int(os.environ.get("RAG_CHUNK_OVERLAP", "128"))
    """Overlap between consecutive chunks in tokens."""

    # ------------------------------------------------------------------
    # Embedding model
    # ------------------------------------------------------------------
    embedding_model_name: str = os.environ.get(
        "RAG_EMBEDDING_MODEL", "BAAI/bge-base-en-v1.5"
    )
    """HuggingFace SentenceTransformer model for dense embeddings."""

    embedding_dim: int = 768
    """Output dimension of bge-base-en-v1.5. Matches the model's hidden size."""

    embedding_device: str = field(default_factory=lambda: os.environ.get(
        "RAG_EMBEDDING_DEVICE",
        _detect_best_device(),
    ))
    """Device for SentenceTransformer: 'cpu', 'cuda', 'cuda:0', or 'mps'."""

    # ------------------------------------------------------------------
    # E5 model prefix (v0.4)
    # ------------------------------------------------------------------
    embedding_query_prefix: str = os.environ.get(
        "RAG_EMBEDDING_QUERY_PREFIX", ""
    )
    """Prefix added before query text during encoding.
    For E5 models: 'query: '. For vanilla BGE: leave empty."""

    embedding_passage_prefix: str = os.environ.get(
        "RAG_EMBEDDING_PASSAGE_PREFIX", ""
    )
    """Prefix added before document text during encoding.
    For E5 models: 'passage: '. For vanilla BGE: leave empty."""

    # ------------------------------------------------------------------
    # Retrieval parameters
    # ------------------------------------------------------------------
    top_k: int = int(os.environ.get("RAG_TOP_K", "5"))
    """Default number of chunks to retrieve per query."""

    rrf_k: int = int(os.environ.get("RAG_RRF_K", "60"))
    """RRF rank-smoothing constant. 60 is the standard from TREC literature."""

    faiss_search_k: int = int(os.environ.get("RAG_FAISS_SEARCH_K", "100"))
    """Number of FAISS candidates to fetch before RRF fusion (should be > top_k)."""

    bm25_search_k: int = int(os.environ.get("RAG_BM25_SEARCH_K", "100"))
    """Number of BM25 candidates to fetch before RRF fusion (should be > top_k)."""

    # ------------------------------------------------------------------
    # LLM configuration
    # ------------------------------------------------------------------
    llm_provider: str = os.environ.get("RAG_LLM_PROVIDER", "openai")
    """LLM backend: 'openai' or 'anthropic'."""

    llm_model: str = os.environ.get("RAG_LLM_MODEL", "gpt-4o-mini")
    """Model name passed to the provider's API."""

    llm_temperature: float = float(os.environ.get("RAG_LLM_TEMPERATURE", "0.0"))
    """Sampling temperature. 0.0 = deterministic (recommended for RAG)."""

    llm_max_tokens: int = int(os.environ.get("RAG_LLM_MAX_TOKENS", "1024"))
    """Maximum tokens in LLM response."""

    streaming_enabled: bool = os.environ.get("RAG_STREAMING_ENABLED", "true").lower() in (
        "true", "1", "yes"
    )
    """Enable streaming output in Gradio UI. Default True."""

    # ------------------------------------------------------------------
    # Workflow control
    # ------------------------------------------------------------------
    max_retries: int = int(os.environ.get("RAG_MAX_RETRIES", "3"))
    """Maximum retrieval retry attempts before forced answer generation."""

    # ------------------------------------------------------------------
    # OCR settings (used by data_prepare.py)
    # ------------------------------------------------------------------
    ocr_language: str = os.environ.get(
        "RAG_OCR_LANGUAGE", "fra+eng+deu+ita+spa"
    )
    """Tesseract language pack string for OCR of scanned PDFs."""

    ocr_dpi: int = int(os.environ.get("RAG_OCR_DPI", "300"))
    """DPI for pdf2image rendering before OCR."""

    # ------------------------------------------------------------------
    # Semantic cache (v0.4)
    # ------------------------------------------------------------------
    cache_enabled: bool = os.environ.get("RAG_CACHE_ENABLED", "true").lower() == "true"
    """Enable semantic caching of (question, answer) pairs."""

    cache_similarity_threshold: float = float(
        os.environ.get("RAG_CACHE_SIMILARITY_THRESHOLD", "0.92")
    )
    """Cosine similarity threshold for semantic cache hit."""

    cache_redis_url: str = os.environ.get(
        "RAG_CACHE_REDIS_URL", "redis://localhost:6379/0"
    )
    """Redis connection URL for persistent cache storage."""

    cache_max_size: int = int(os.environ.get("RAG_CACHE_MAX_SIZE", "10000"))
    """Maximum number of cached entries."""

    cache_ttl: int = int(os.environ.get("RAG_CACHE_TTL", "86400"))
    """Cache entry TTL in seconds (default: 24 hours)."""

    # ------------------------------------------------------------------
    # Re-ranker (v0.4)
    # ------------------------------------------------------------------
    reranker_enabled: bool = os.environ.get("RAG_RERANKER_ENABLED", "true").lower() == "true"
    """Enable cross-encoder re-ranking after retrieval."""

    reranker_model: str = os.environ.get(
        "RAG_RERANKER_MODEL", "BAAI/bge-reranker-base"
    )
    """Cross-encoder model for re-ranking retrieved documents."""

    reranker_top_k: int = int(os.environ.get("RAG_RERANKER_TOP_K", "5"))
    """Number of documents to keep after re-ranking."""

    reranker_max_length: int = int(os.environ.get("RAG_RERANKER_MAX_LENGTH", "512"))
    """Max characters per document sent to the cross-encoder."""

    # ------------------------------------------------------------------
    # Logging
    # ------------------------------------------------------------------
    log_level: str = os.environ.get("RAG_LOG_LEVEL", "INFO")
    """Logging level: DEBUG, INFO, WARNING, ERROR."""


    # ------------------------------------------------------------------
    # Runtime override
    # ------------------------------------------------------------------

    def from_dict(self, overrides: dict) -> "RAGConfig":
        """Return a new RAGConfig with selected fields overridden.

        Keys use the Python attribute names (lowercase), e.g.:
            {"top_k": 10, "llm_temperature": 0.5}

        Invalid keys are silently ignored. Returns a copy — the original
        config is not mutated.

        Args:
            overrides: Dict mapping attribute names to new values.

        Returns:
            A new RAGConfig instance with the specified fields replaced.
        """
        import copy
        new_config = copy.deepcopy(self)
        for key, value in overrides.items():
            if hasattr(new_config, key):
                setattr(new_config, key, value)
        return new_config


# ------------------------------------------------------------------
# Singleton instance — import this everywhere
# ------------------------------------------------------------------
config = RAGConfig()
